name : destroy
on :
  # push : 
  #   branches : ["master"]
  
  workflow_dispatch:
    inputs : 
      region :
        description: "Enter your region name : "
        required: true  
        type: string    

env :
  bucket : aarushi-backend2
  tfstate_file : new.tfstate
  region: ${{ github.event.inputs.region }}

jobs :
  destroy : 
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Terraform hashicorp setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.region }}

      - name : init
        run: |
          cd S3
          terraform init 

      - name: destroy
        run: |
          cd S3
          terraform destroy -auto-approve 